### ISSUE TITLE
Compatibility with Russian translation

### ISSUE THREAD

**Issue by miegir** [arsym-dev/428-Text-Speed-Patch#1] opened 2024-03-04 22:25 UTC
Hello. I have translated the game into Russian and one of the users asks about compatibility with your patch. I am only patching .wad files. And with your patch I see that the text displayed properly but not speeds up. Do you have any idea why this might happen?

**Comment by arsym-dev** [comment] 2024-03-04 23:08
Can you confirm if the 2x version works at least? The instant version is a bit more complex and may have issues, but the 2x fix should be fine. This can help gauge where the problem is.

**Comment by arsym-dev** [comment] 2024-03-04 23:36
Is there an easy way to download/use the Russian translation? I see the files in your repository but they seem to be unpacked. How can I use them?

**Comment by miegir** [comment] 2024-03-05 07:52
You can download translation from https://github.com/miegir/ShibuyaTools/releases as win-x64.7z, unpack it and launch contained exe (installer). In installer, you can select the path to the game executable and press the Roll button. To uninstall the translation, lauch the installer again and press Unroll button.

It seems to me that 2x patch works, but instant has the same effect as 2x.

**Comment by no1name0000000** [comment] 2024-03-05 09:17
> Can you confirm if the 2x version works at least? The instant version is a bit more complex and may have issues, but the 2x fix should be fine. This can help gauge where the problem is.

The VN text does not have a uniform speed, it can be faster or slower, but with the patch these chips disappear. And with the patch for instant text output, the backlogs also break down, they begin to be output gradually.

Patch x2, in my opinion, has not changed the basic speed of the text.

**Comment by arsym-dev** [comment] 2024-03-05 15:08
Please try the v1.01 release and confirm that "instant" now works as expected.
[https://github.com/arsym-dev/428-Text-Speed-Patch/releases](https://github.com/arsym-dev/428-Text-Speed-Patch/releases)

Make sure to rename "428 Shibuya Scramble-instant.exe" to "428 Shibuya Scramble.exe" before running.

**Comment by miegir** [comment] 2024-03-05 21:20
Instant v1.01 is indeed instant now in the story. But, as @no1name0000000 mentioned, backlog, that is instant with the original, is not instant with the patch. I made short video capture, and 2x seems to work exactly as original without speedup.
[original.mp4](https://github.com/arsym-dev/428-Text-Speed-Patch/assets/7460974/bf21e8b7-9ef3-46cc-a8f4-9178d957c186)  
   [2x.mp4](https://github.com/arsym-dev/428-Text-Speed-Patch/assets/7460974/cc8fd825-7463-4e6c-8377-e04ac79c65b8) 
  [instant.mp4](https://github.com/arsym-dev/428-Text-Speed-Patch/assets/7460974/a2cd8c5f-2c9b-47c9-922a-fd47b1857f0f)

**Comment by arsym-dev** [comment] 2024-03-06 03:51
- 2x seems to not work with languages that use more than one byte per character.
- I tried today to fix the instant backlog but had no luck. The backlog has been a known issue for a long time and there are no plans to resolve it since the text still appears very quickly. The slowdown just happens on new lines which isn't the worst thing.

I'm going to close this issue. Now that it works with other languages, please use "instant" if you'd like to speed up text in the game. I hope it makes playing more enjoyable!

**Closed as completed by arsym-dev** 2024-03-06 03:51 UTC

**Comment by miegir** [comment] 2024-03-06 07:09
Thanks for your work.
